### PR TITLE
Update peerDependencies to support newer versions of graphql

### PR DESCRIPTION
**Pull request by kachkaev**

### CODE REVIEW

**Comment by kachkaev** [comment]
@helfer do you still recommend using this package? Or is there anything newer that replaces it?

**Comment by kachkaev** [comment]
Perhaps, it'd be even better if `graphql` stopped being in `dependencies` of this package. Currently having problems in a project that uses graphql 0.12 or 0.13.

**Comment by moltar** [comment]
I don't think having a peer dependency is a good solution. I am currently using a framework package, that wraps `graphql` (thus I am not depending on it directly), but I also want to use `graphql-disable-introspection` with it. Everything works fine, but I am always getting npm warnings.

**Comment by helfer** [comment]
@kachkaev @moltar I've updated the peer-dependency versions and published version 1.1.0.

**Pull request merged**
